version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app # Эта строка позволяет синхронизировать файлы между локальной машиной и контейнером

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_db
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db_data:
